Club Design update
sed-group/sed-backend pull request #71
Opened 2023-04-13 19:42 UTC by obennet

Updates the API to contain end-points required to operate the new SED Lab "Club Design" application.

2023-04-21 08:10 UTC, johnmartins requested changes
Looks OK, but there are some minor things that needs to be fixed. Also, I'm worried about the simulations taking up computational resources. We should evaluate the possibilities of running the expensive stuff on separate services

2023-04-21 08:10 UTC, johnmartins commented on sedbackend/apps/cvs/simulation/storage.py
It looks like the simulations run through this code are synchronous. Have you tried running these simulations with more than 1 user logged in? How does it impact performance? If these simulations are computationally expensive we should be running them on a separate service.

2023-04-21 08:10 UTC, johnmartins commented on sedbackend/libs/parsing/expressions.py
Can we rename this parsing sub-lib to something a bit more clear? What exactly does it parse? "Parsing" as a lib name is very generic

2023-04-25 14:17 UTC, EppChops commented on .github/ISSUE_TEMPLATE/bug_report.md
Removed.

2023-04-25 14:17 UTC, EppChops commented on .github/ISSUE_TEMPLATE/feature_request.md
Removed.

2023-04-25 14:20 UTC, EppChops commented on sedbackend/libs/parsing/expressions.py
Would "formula_parser" be a more fitting name?

It parses the formulas as mathematical expressions, from the "link_design_lifecycle" module to the "simulation" module.

2023-04-25 14:32 UTC, EppChops commented on sedbackend/apps/cvs/simulation/storage.py
We have not tried to run the simulations with more than 1 person logged in at the same time. I would imagine it could have an effect on the performance. As of now however if we run the simple simulation, it will only run on one core, which is still a bit slow. Could try this out on Thursday perhaps?

The simulations are quite computationally expensive, especially if the "multiprocessing" option is used which parallelizes the work on all cores. Looking into having the simulation running on a separate service seems quite good. Maybe move to a separate docker container?

Also, currently it will lock the user out of doing any other work if a simulation has been started. Something that we should fix over time.

2023-05-04 09:28 UTC, johnmartins approved these changes
OK

2023-05-04 10:28 UTC, merged